API_KEY exception handled
output = float(amount * get_currency("EUR_USD"))
TypeError: get_currency() missing 1 required positional argument: 'api_key'